### PR TITLE
Add link to Reddit

### PR DESCRIPTION
**Pull request by ravage84**
Don't use Reddit myself but I know it's quite popular.Thought it makes sense.

### CODE REVIEW

**Comment by ravage84** [comment]
I guess the community.cakephp.org page needs to be updated manually?

**Comment by lorenzo** [comment]
mmm, I think so :(

**Comment by lorenzo** [comment]
@phpnut do you have an idea of how to deploy this site?

**Comment by phpnut** [comment]
@lorenzo I will get it updated then I get home, I believe it is just a pull on the server.

**Comment by ravage84** [comment]
Would it make sense to integrate this code into the main cakephp.org page repo? This way we could sync the appearance and it would make updating probably easier.

**Comment by phpnut** [comment]
Site it updated. It looks like fabric is used to this site.
@ravage84 I am planning on revamping a lot of the sites this coming year and trying to get rid of useless things we are not using and no one has interest in maintaining. Plans is the make it easier to manage.

**Pull request merged**
